### ISSUE TITLE
Use Pybind11 for rclpy Python Bindings

### ISSUE THREAD

**Issue by sloretz** [ros2/rclpy#665]
## Feature request

@azeey @iantheengineer @cottsay FYI

#### Feature description

This is a ticket to use Pybind11 for the CPython extension instead of manually writing code to interact with the CPython API.

#### Implementation considerations

Plan: https://docs.google.com/document/d/1BsTlxgzAkpX-5Q7FW6_Hyw1fszDEQef_OEvYmdnrBrE/edit?usp=sharing

- [x] Replace custom CMake with Pybind11's pybind11_add_module (#667)
    - [x] Investigate CMake issues in Windows Debug https://github.com/ros2/rclpy/pull/667#issuecomment-778687182
    - [x] Fix windows warning reported in #687, (#688)
    - [ ] Remove code unsetting Py_DEBUG definition once all modules use Pybind11 (https://github.com/ros2/rclpy/pull/681#issuecomment-784579212) #814
- [ ] Convert each module to use Pybind11 with the existing C to Python API
    - [x] _rclpy (#675 :heavy_check_mark:, #691 :heavy_check_mark:, #692 :heavy_check_mark:, #693 :heavy_check_mark:, #694 :heavy_check_mark:, #695 :heavy_check_mark:, #696 :heavy_check_mark:, #699 :heavy_check_mark:, #701 :heavy_check_mark:, #703 :heavy_check_mark:, #706 :heavy_check_mark: , #709 :heavy_check_mark: , #712 :heavy_check_mark: , #715 :heavy_check_mark: , #717 :heavy_check_mark: , #718 :heavy_check_mark: , #719 :heavy_check_mark:, #721 :heavy_check_mark: , #723 :heavy_check_mark:, #730 :heavy_check_mark: , #732 :heavy_check_mark: , #733 :heavy_check_mark:, #735 :heavy_check_mark:, #736 :heavy_check_mark:, #738 :heavy_check_mark:)
    - [x] _rclpy_action (#678)
    - [x] _rclpy_handle (#668)
    - [x] _rclpy_logging (#659)
    - [x] _rclpy_pycapsule (#652)
    - [ ] _rclpy_signal_handler (#728)
        - skipping - uses C atomic types that can't be used with C++ due to [p0943r1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0943r1.html) #814
        - Actually, couldn't skip because it uses rclpy_common, so rewrote in Python.
    - [ ] _rclpy_common (Common library, not a module, started in #675 :heavy_check_mark:, #727 :heavy_check_mark:, #743) #814
- [ ] Replace checking `rcl_ret_t` with `void throw_if_not_ok(rcl_ret_t ret, const std::string & extra_error_msg);`
    - [x] Or use RCLError(), like #685 does for _rclpy_action
- [x] Refactor rclpy objects to use C++ classes one object at a time, leaf objects first
    - [x] rcl_time_point_t -> bind struct #737
    - [x] rmw_service_info_t -> bind struct (#748)
    - [x] rcl_duration_t -> bind struct (claimed) https://github.com/ros2/rclpy/pull/744
    - [x] rmw_qos_profile_t -> bind struct (#741)
    - [x] rmw_request_id_t -> bind struct (#748)
    - [x] rcl_wait_set_t -> not sure if rclpy::WaitSet or bind struct (maybe tricky) (#769)
    - [x] rclpy_client_t -> rclpy::Client (#739)
    - [x] rclpy_service_t -> rclpy::Service (#747)
    - [x] rcl_guard_condition_t -> rclpy::GuardCondition #772 (for H-turtle [branch]( https://github.com/ros2/rclpy/tree/ahcorde/pybind11-guardcondition))
    - [x] rcl_event_t -> rclpy::Event (#750)
    - [x] rclpy_publisher_t -> rclpy::Publisher (#756)
    - [x] rclpy_subscription_t -> rclpy::Subscription (#756)
    - [x] rcl_timer_t -> rclpy::Timer (#745)
    - [x] rcl_clock_t -> rclpy::Clock (#749)
    - [x] rcl_action_client_t -> rclpy::ActionClient (#759)
    - [x] rcl_action_goal_handle_t -> rclpy::ActionGoalHandle (#751, #767)
    - [x] rcl_action_server_t -> rclpy::ActionServer (#766)
    - [x] rcl_node_t -> rclpy::Node (#771)
    - [x] rcl_context_t -> rclpy::Context (#771)

Refactor order:  Arrows point from a type that needs to be refactored before the type it points to. Types with no arrows pointing them can be done as soon as all methods using them are converted to pybind11.

![pybind11_conversion_graph](https://user-images.githubusercontent.com/4175662/112526380-1cd40a80-8d5f-11eb-8b6b-9be464547579.png)
<details><summary>dot graph of order</summary>

```dot
digraph order_of_conversions {
rcl_time_point_t
rcl_wait_set_t
rmw_qos_profile_t
rmw_request_id_t
rmw_service_info_t
rcl_duration_t
action_client -> rcl_node_t
action_server -> rcl_node_t
rcl_action_goal_handle_t -> action_server
rcl_node_t -> context
subscription -> rcl_node_t
publisher -> rcl_node_t
service -> rcl_node_t
client -> rcl_node_t
timer -> context
timer -> clock
clock
guard_condition -> context
rcl_event_t -> publisher
rcl_event_t -> subscription
}
```
</details>

**Comment by clalancette** [comment]
@sloretz Given that we've gone as far as we are going to go with this in Galactic, should we remove this ticket from the Galactic Project board and move it to the H-Turtle one?

**Comment by sloretz** [comment]
> @sloretz Given that we've gone as far as we are going to go with this in Galactic, should we remove this ticket from the Galactic Project board and move it to the H-Turtle one?

I would keep it in Galactic. Our current plan is to backport the remainder of the work to Galactic for the first patch release.

**Comment by wjwwood** [comment]
> I would keep it in Galactic. Our current plan is to backport the remainder of the work to Galactic for the first patch release.

Should we (created and then) move it to a 'Galactic Patch Release 1' project board? I think we've done something like that in the past.

**Comment by clalancette** [comment]
> Should we (created and then) move it to a 'Galactic Patch Release 1' project board? I think we've done something like that in the past.

That makes sense to me.  @cottsay Mind doing that?

**Comment by ahcorde** [comment]
Related work

 - [ ] Remove `rclpy_common` by eliminating any use of the C api's in `rclpy_common` for the C++ ones that use pybind11
 - [ ] Move exceptions.hpp/exceptions.cpp to the `_rclpy_pybind11` module
 - [ ] Delele `handle.hpp/handle.cpp` as they should no longer be used
